// Vercel serverless function to substitute environment variables
export default function handler(req, res) {
  // Set proper headers for JavaScript file
  res.setHeader('Content-Type', 'application/javascript');
  res.setHeader('Cache-Control', 'no-cache');
  
  // Get environment variables with fallbacks
  const moralisApiKey = process.env.MORALIS_API_KEY || process.env.NEXT_PUBLIC_MORALIS_API_KEY || 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJub25jZSI6IjkzNmEwYmYzLWE3NTEtNDI5Ni1hNmFkLTRhNTlhZDc1NjE4MCIsIm9yZ0lkIjoiNDY0Mzk2IiwidXNlcklkIjoiNDc3NzYxIiwidHlwZUlkIjoiYzVlMTk4ZTgtNTAzNy00YjcxLWFkNGItYTAyOTU4MDcyYmFiIiwidHlwZSI6IlBST0pFQ1QiLCJpYXQiOjE3NTQ4NTA2NjQsImV4cCI6NDkxMDYxMDY2NH0.MPO2RBT_JWZR6laF8VkAXMxUx7f6-U9_ueCJuNdbe8I';
  const moralisServerUrl = process.env.MORALIS_SERVER_URL || process.env.NEXT_PUBLIC_MORALIS_SERVER_URL || 'https://solana-gateway.moralis.io';
  const moralisAppId = process.env.MORALIS_APP_ID || process.env.NEXT_PUBLIC_MORALIS_APP_ID || 'genesis-web3-app';
  
  // Generate the JavaScript config file content
  const configContent = `// API Configuration - Generated by Vercel with Environment Variables
// This file is dynamically generated with environment variables

const API_CONFIG = {
    // ========================================
    // TWITTER/X API INTEGRATION
    // ========================================
    TWITTER: {
        BEARER_TOKEN: '${process.env.TWITTER_BEARER_TOKEN || 'AAAAAAAAAAAAAAAAAAAAANg%2F3QEAAAAA%2BSxUcI63SO8FPw%2FzUPrJwioczuU%3D4xz52vuOqFZjJwpSQz6Fv3PUk5EzOzbXjQNixglhytz5DYp5ME'}',
        API_BASE_URL: 'https://api.twitter.com/2',
    },

    // ========================================
    // INSTAGRAM API INTEGRATION        
    // ========================================
    INSTAGRAM: {
        ACCESS_TOKEN: '${process.env.INSTAGRAM_ACCESS_TOKEN || 'YOUR_INSTAGRAM_ACCESS_TOKEN'}',
        API_BASE_URL: 'https://graph.instagram.com',
    },

    // ========================================
    // YOUTUBE API INTEGRATION
    // ========================================
    YOUTUBE: {
        API_KEY: '${process.env.YOUTUBE_API_KEY || 'AIzaSyB54sr1jQzA9rhCww6Ha7KDaqFa1CMF2Y0'}',
        API_BASE_URL: 'https://www.googleapis.com/youtube/v3',
    },

    // ========================================
    // STORAGE & DATABASE
    // ========================================
    FIREBASE: {
        apiKey: '${process.env.FIREBASE_API_KEY || 'YOUR_FIREBASE_API_KEY'}',
        authDomain: '${process.env.FIREBASE_AUTH_DOMAIN || 'your-project.firebaseapp.com'}',
        projectId: '${process.env.FIREBASE_PROJECT_ID || 'your-project-id'}',
        storageBucket: '${process.env.FIREBASE_STORAGE_BUCKET || 'your-project.appspot.com'}',
        messagingSenderId: '${process.env.FIREBASE_MESSAGING_SENDER_ID || 'your-sender-id'}',
        appId: '${process.env.FIREBASE_APP_ID || 'your-app-id'}'
    },

    AWS: {
        REGION: '${process.env.AWS_REGION || 'us-east-1'}',
        BUCKET_NAME: '${process.env.AWS_BUCKET_NAME || 'your-bucket-name'}',
        ACCESS_KEY_ID: '${process.env.AWS_ACCESS_KEY_ID || 'YOUR_AWS_ACCESS_KEY'}',
        SECRET_ACCESS_KEY: '${process.env.AWS_SECRET_ACCESS_KEY || 'YOUR_AWS_SECRET_KEY'}'
    },

    MONGODB: {
        CONNECTION_STRING: '${process.env.MONGODB_CONNECTION_STRING || 'YOUR_MONGODB_CONNECTION_STRING'}'
    },

    // ========================================
    // MORALIS WEB3 AUTHENTICATION
    // ========================================
    MORALIS: {
        API_KEY: '${moralisApiKey}',
        SERVER_URL: '${moralisServerUrl}',
        APP_ID: '${moralisAppId}',
    },

    // ========================================
    // DEVELOPMENT vs PRODUCTION
    // ========================================
    ENVIRONMENT: 'production',
    USE_MOCK_DATA: false,
};

// Environment check for production
if (typeof window !== 'undefined' && window.location.hostname !== 'localhost') {
    API_CONFIG.ENVIRONMENT = 'production';
    API_CONFIG.USE_MOCK_DATA = false;
}

// Export for use in other modules
if (typeof module !== 'undefined' && module.exports) {
    module.exports = API_CONFIG;
}`;

  // Send the JavaScript content
  res.status(200).send(configContent);
}